id: PD1E35846
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: fr
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    1fbbc01c9eed4dcdaa1c6ed0a08229bd:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    367117d828184c3a9643462a7b8de91c:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    9e75b6bae5c54e9bbc04bada28519416:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    c56417bb7b5a4368ae6d7c85f1ca6719:
      title: Praise to Mañjughoṣa
      parent: Praise
    769b4e783d62415e8a4821d7f57565ff:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    3573584a2ee74ddebb8ceb48407492e3:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    a0320e7908f4411982d71c037ee8efbe:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    33e752c923354c01957c7505ff3e32d9:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.974232'
last_modified_at: '2022-03-01T01:55:51.974235'
